name: Java CI

on:
  push:
    branches: [ "main", "dev-feature"]
  pull_request:
    branches: [ "main" ]

jobs:
  checkstyle:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
      - run: make checkstyle
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
          java-version: 17
          distribution: 'temurin'
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
    #- run: make checkstyle
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
          arguments: build
          build-root-directory: ./
    
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
      env:
         CC_TEST_REPORTER_ID: ${{secrets.CODECLIMAT_TEST_COVERAGE}}
         JACOCO_SOURCE_PATH: ./app/src/main/java
      with:
         coverageCommand: make report
         coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
