# file: .github/workflows/hello-world.yml
name: checkstyle




on: push
jobs:
  say-hello:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: make checkstyle
